/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var i=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var n=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var f=(s,e)=>{for(var a in e)i(s,a,{get:e[a],enumerable:!0})},l=(s,e,a,t)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of n(e))!h.call(s,o)&&o!==a&&i(s,o,{get:()=>e[o],enumerable:!(t=r(e,o))||t.enumerable});return s};var d=s=>l(i({},"__esModule",{value:!0}),s);var k={};f(k,{default:()=>c});module.exports=d(k);var p=require("obsidian"),c=class extends p.Plugin{async onload(){this.registerEvent(this.app.workspace.on("layout-change",()=>{this.enforceSingleTab()})),this.app.workspace.onLayoutReady(()=>{this.enforceSingleTab()})}enforceSingleTab(){let e=[];if(this.app.workspace.iterateRootLeaves(a=>{e.push(a)}),e.length>1){let a=this.app.workspace.activeLeaf;a&&e.includes(a)?e.forEach(t=>{t!==a&&t.detach()}):e.slice(1).forEach(t=>t.detach())}}};
